org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
kotlin.code.style=official
android.enableDexingArtifactTransform=false
org.gradle.vfs.watch=false
org.gradle.daemon=false
android.enableResourceOptimizations=false
