services:
  - type: web
    name: agriconnect-backend
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        value: "postgresql://postgres.bgcgmmrmakgvuiozqvjy:AgriConnect123.@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require"
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ADMIN_MOBILE
        value: "9999999999"
      - key: ADMIN_PASSWORD
        value: "Admin123!"
