pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AgriConnect"
include ':app'
project(':app').projectDir = file('frontend/android/app')

// Creating the new data module for backend connection
include ':data'
project(':data').projectDir = file('frontend/android/data')

// Use a build directory outside of OneDrive to avoid AccessDeniedException (File Locking)
def tempBuildDir = "C:/temp/AgriConnect"

gradle.beforeProject { project ->
    def subPath = project.path == ":" ? "root" : project.path.replace(':', '_')
    project.layout.buildDirectory.set(file("${tempBuildDir}/${subPath}"))
}

